// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StateDevice.proto

package com.alfred.common.messages;

public final class StateDeviceProtos {
  private StateDeviceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StateDeviceMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alfred.common.messages.StateDeviceMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
     */
    com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type getType();

    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
     */
    boolean hasState();
    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
     */
    com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State getState();

    /**
     * <code>optional int32 value = 5;</code>
     */
    boolean hasValue();
    /**
     * <code>optional int32 value = 5;</code>
     */
    int getValue();

    /**
     * <code>optional bytes data = 6;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 6;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code com.alfred.common.messages.StateDeviceMessage}
   */
  public static final class StateDeviceMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.alfred.common.messages.StateDeviceMessage)
      StateDeviceMessageOrBuilder {
    // Use StateDeviceMessage.newBuilder() to construct.
    private StateDeviceMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StateDeviceMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StateDeviceMessage defaultInstance;
    public static StateDeviceMessage getDefaultInstance() {
      return defaultInstance;
    }

    public StateDeviceMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StateDeviceMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type value = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State value = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                state_ = value;
              }
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              value_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateDeviceMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateDeviceMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.class, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<StateDeviceMessage> PARSER =
        new com.google.protobuf.AbstractParser<StateDeviceMessage>() {
      public StateDeviceMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StateDeviceMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StateDeviceMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code com.alfred.common.messages.StateDeviceMessage.Type}
     */
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DOORBELL = 0;</code>
       */
      DOORBELL(0, 0),
      /**
       * <code>GARAGEDOOR = 1;</code>
       */
      GARAGEDOOR(1, 1),
      /**
       * <code>LIGHT = 2;</code>
       */
      LIGHT(2, 2),
      /**
       * <code>CEILINGFAN = 3;</code>
       */
      CEILINGFAN(3, 3),
      /**
       * <code>OUTLET = 4;</code>
       */
      OUTLET(4, 4),
      ;

      /**
       * <code>DOORBELL = 0;</code>
       */
      public static final int DOORBELL_VALUE = 0;
      /**
       * <code>GARAGEDOOR = 1;</code>
       */
      public static final int GARAGEDOOR_VALUE = 1;
      /**
       * <code>LIGHT = 2;</code>
       */
      public static final int LIGHT_VALUE = 2;
      /**
       * <code>CEILINGFAN = 3;</code>
       */
      public static final int CEILINGFAN_VALUE = 3;
      /**
       * <code>OUTLET = 4;</code>
       */
      public static final int OUTLET_VALUE = 4;


      public final int getNumber() { return value; }

      public static Type valueOf(int value) {
        switch (value) {
          case 0: return DOORBELL;
          case 1: return GARAGEDOOR;
          case 2: return LIGHT;
          case 3: return CEILINGFAN;
          case 4: return OUTLET;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Type[] VALUES = values();

      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.alfred.common.messages.StateDeviceMessage.Type)
    }

    /**
     * Protobuf enum {@code com.alfred.common.messages.StateDeviceMessage.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ON = 0;</code>
       */
      ON(0, 0),
      /**
       * <code>OFF = 1;</code>
       */
      OFF(1, 1),
      /**
       * <code>ACTIVE = 2;</code>
       */
      ACTIVE(2, 2),
      /**
       * <code>INACTIVE = 3;</code>
       */
      INACTIVE(3, 3),
      /**
       * <code>OPEN = 4;</code>
       */
      OPEN(4, 4),
      /**
       * <code>CLOSED = 5;</code>
       */
      CLOSED(5, 5),
      ;

      /**
       * <code>ON = 0;</code>
       */
      public static final int ON_VALUE = 0;
      /**
       * <code>OFF = 1;</code>
       */
      public static final int OFF_VALUE = 1;
      /**
       * <code>ACTIVE = 2;</code>
       */
      public static final int ACTIVE_VALUE = 2;
      /**
       * <code>INACTIVE = 3;</code>
       */
      public static final int INACTIVE_VALUE = 3;
      /**
       * <code>OPEN = 4;</code>
       */
      public static final int OPEN_VALUE = 4;
      /**
       * <code>CLOSED = 5;</code>
       */
      public static final int CLOSED_VALUE = 5;


      public final int getNumber() { return value; }

      public static State valueOf(int value) {
        switch (value) {
          case 0: return ON;
          case 1: return OFF;
          case 2: return ACTIVE;
          case 3: return INACTIVE;
          case 4: return OPEN;
          case 5: return CLOSED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<State>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private State(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.alfred.common.messages.StateDeviceMessage.State)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type type_;
    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
     */
    public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type getType() {
      return type_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State state_;
    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
     */
    public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State getState() {
      return state_;
    }

    public static final int VALUE_FIELD_NUMBER = 5;
    private int value_;
    /**
     * <code>optional int32 value = 5;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 value = 5;</code>
     */
    public int getValue() {
      return value_;
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 6;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes data = 6;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private void initFields() {
      id_ = "";
      name_ = "";
      type_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type.DOORBELL;
      state_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State.ON;
      value_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, state_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, data_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, state_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, value_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alfred.common.messages.StateDeviceMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alfred.common.messages.StateDeviceMessage)
        com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateDeviceMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateDeviceMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.class, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder.class);
      }

      // Construct using com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type.DOORBELL;
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State.ON;
        bitField0_ = (bitField0_ & ~0x00000008);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateDeviceMessage_descriptor;
      }

      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage getDefaultInstanceForType() {
        return com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.getDefaultInstance();
      }

      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage build() {
        com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage buildPartial() {
        com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage result = new com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage) {
          return mergeFrom((com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage other) {
        if (other == com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type type_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type.DOORBELL;
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
       */
      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type getType() {
        return type_;
      }
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
       */
      public Builder setType(com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.Type type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Type.DOORBELL;
        onChanged();
        return this;
      }

      private com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State state_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State.ON;
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
       */
      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State getState() {
        return state_;
      }
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
       */
      public Builder setState(com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.alfred.common.messages.StateDeviceMessage.State state = 4;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.State.ON;
        onChanged();
        return this;
      }

      private int value_ ;
      /**
       * <code>optional int32 value = 5;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 value = 5;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional int32 value = 5;</code>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000010;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 value = 5;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000010);
        value_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 6;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.alfred.common.messages.StateDeviceMessage)
    }

    static {
      defaultInstance = new StateDeviceMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.alfred.common.messages.StateDeviceMessage)
  }

  public interface StateListMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.alfred.common.messages.StateListMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    java.util.List<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage> 
        getDeviceList();
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage getDevice(int index);
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    int getDeviceCount();
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    java.util.List<? extends com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder> 
        getDeviceOrBuilderList();
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder getDeviceOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.alfred.common.messages.StateListMessage}
   */
  public static final class StateListMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.alfred.common.messages.StateListMessage)
      StateListMessageOrBuilder {
    // Use StateListMessage.newBuilder() to construct.
    private StateListMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StateListMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StateListMessage defaultInstance;
    public static StateListMessage getDefaultInstance() {
      return defaultInstance;
    }

    public StateListMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StateListMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                device_ = new java.util.ArrayList<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              device_.add(input.readMessage(com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          device_ = java.util.Collections.unmodifiableList(device_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateListMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateListMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alfred.common.messages.StateDeviceProtos.StateListMessage.class, com.alfred.common.messages.StateDeviceProtos.StateListMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<StateListMessage> PARSER =
        new com.google.protobuf.AbstractParser<StateListMessage>() {
      public StateListMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StateListMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StateListMessage> getParserForType() {
      return PARSER;
    }

    public static final int DEVICE_FIELD_NUMBER = 1;
    private java.util.List<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage> device_;
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    public java.util.List<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage> getDeviceList() {
      return device_;
    }
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    public java.util.List<? extends com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder> 
        getDeviceOrBuilderList() {
      return device_;
    }
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    public int getDeviceCount() {
      return device_.size();
    }
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage getDevice(int index) {
      return device_.get(index);
    }
    /**
     * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
     */
    public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder getDeviceOrBuilder(
        int index) {
      return device_.get(index);
    }

    private void initFields() {
      device_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDeviceCount(); i++) {
        if (!getDevice(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < device_.size(); i++) {
        output.writeMessage(1, device_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < device_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, device_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alfred.common.messages.StateDeviceProtos.StateListMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alfred.common.messages.StateDeviceProtos.StateListMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.alfred.common.messages.StateListMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.alfred.common.messages.StateListMessage)
        com.alfred.common.messages.StateDeviceProtos.StateListMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateListMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateListMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alfred.common.messages.StateDeviceProtos.StateListMessage.class, com.alfred.common.messages.StateDeviceProtos.StateListMessage.Builder.class);
      }

      // Construct using com.alfred.common.messages.StateDeviceProtos.StateListMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeviceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (deviceBuilder_ == null) {
          device_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          deviceBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alfred.common.messages.StateDeviceProtos.internal_static_com_alfred_common_messages_StateListMessage_descriptor;
      }

      public com.alfred.common.messages.StateDeviceProtos.StateListMessage getDefaultInstanceForType() {
        return com.alfred.common.messages.StateDeviceProtos.StateListMessage.getDefaultInstance();
      }

      public com.alfred.common.messages.StateDeviceProtos.StateListMessage build() {
        com.alfred.common.messages.StateDeviceProtos.StateListMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alfred.common.messages.StateDeviceProtos.StateListMessage buildPartial() {
        com.alfred.common.messages.StateDeviceProtos.StateListMessage result = new com.alfred.common.messages.StateDeviceProtos.StateListMessage(this);
        int from_bitField0_ = bitField0_;
        if (deviceBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            device_ = java.util.Collections.unmodifiableList(device_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.device_ = device_;
        } else {
          result.device_ = deviceBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alfred.common.messages.StateDeviceProtos.StateListMessage) {
          return mergeFrom((com.alfred.common.messages.StateDeviceProtos.StateListMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alfred.common.messages.StateDeviceProtos.StateListMessage other) {
        if (other == com.alfred.common.messages.StateDeviceProtos.StateListMessage.getDefaultInstance()) return this;
        if (deviceBuilder_ == null) {
          if (!other.device_.isEmpty()) {
            if (device_.isEmpty()) {
              device_ = other.device_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDeviceIsMutable();
              device_.addAll(other.device_);
            }
            onChanged();
          }
        } else {
          if (!other.device_.isEmpty()) {
            if (deviceBuilder_.isEmpty()) {
              deviceBuilder_.dispose();
              deviceBuilder_ = null;
              device_ = other.device_;
              bitField0_ = (bitField0_ & ~0x00000001);
              deviceBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDeviceFieldBuilder() : null;
            } else {
              deviceBuilder_.addAllMessages(other.device_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDeviceCount(); i++) {
          if (!getDevice(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alfred.common.messages.StateDeviceProtos.StateListMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alfred.common.messages.StateDeviceProtos.StateListMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage> device_ =
        java.util.Collections.emptyList();
      private void ensureDeviceIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          device_ = new java.util.ArrayList<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage>(device_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder> deviceBuilder_;

      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public java.util.List<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage> getDeviceList() {
        if (deviceBuilder_ == null) {
          return java.util.Collections.unmodifiableList(device_);
        } else {
          return deviceBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public int getDeviceCount() {
        if (deviceBuilder_ == null) {
          return device_.size();
        } else {
          return deviceBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage getDevice(int index) {
        if (deviceBuilder_ == null) {
          return device_.get(index);
        } else {
          return deviceBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder setDevice(
          int index, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage value) {
        if (deviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceIsMutable();
          device_.set(index, value);
          onChanged();
        } else {
          deviceBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder setDevice(
          int index, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder builderForValue) {
        if (deviceBuilder_ == null) {
          ensureDeviceIsMutable();
          device_.set(index, builderForValue.build());
          onChanged();
        } else {
          deviceBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder addDevice(com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage value) {
        if (deviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceIsMutable();
          device_.add(value);
          onChanged();
        } else {
          deviceBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder addDevice(
          int index, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage value) {
        if (deviceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDeviceIsMutable();
          device_.add(index, value);
          onChanged();
        } else {
          deviceBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder addDevice(
          com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder builderForValue) {
        if (deviceBuilder_ == null) {
          ensureDeviceIsMutable();
          device_.add(builderForValue.build());
          onChanged();
        } else {
          deviceBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder addDevice(
          int index, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder builderForValue) {
        if (deviceBuilder_ == null) {
          ensureDeviceIsMutable();
          device_.add(index, builderForValue.build());
          onChanged();
        } else {
          deviceBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder addAllDevice(
          java.lang.Iterable<? extends com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage> values) {
        if (deviceBuilder_ == null) {
          ensureDeviceIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, device_);
          onChanged();
        } else {
          deviceBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder clearDevice() {
        if (deviceBuilder_ == null) {
          device_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          deviceBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public Builder removeDevice(int index) {
        if (deviceBuilder_ == null) {
          ensureDeviceIsMutable();
          device_.remove(index);
          onChanged();
        } else {
          deviceBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder getDeviceBuilder(
          int index) {
        return getDeviceFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder getDeviceOrBuilder(
          int index) {
        if (deviceBuilder_ == null) {
          return device_.get(index);  } else {
          return deviceBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public java.util.List<? extends com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder> 
           getDeviceOrBuilderList() {
        if (deviceBuilder_ != null) {
          return deviceBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(device_);
        }
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder addDeviceBuilder() {
        return getDeviceFieldBuilder().addBuilder(
            com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder addDeviceBuilder(
          int index) {
        return getDeviceFieldBuilder().addBuilder(
            index, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.alfred.common.messages.StateDeviceMessage device = 1;</code>
       */
      public java.util.List<com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder> 
           getDeviceBuilderList() {
        return getDeviceFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder> 
          getDeviceFieldBuilder() {
        if (deviceBuilder_ == null) {
          deviceBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessage.Builder, com.alfred.common.messages.StateDeviceProtos.StateDeviceMessageOrBuilder>(
                  device_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          device_ = null;
        }
        return deviceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.alfred.common.messages.StateListMessage)
    }

    static {
      defaultInstance = new StateListMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.alfred.common.messages.StateListMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alfred_common_messages_StateDeviceMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alfred_common_messages_StateDeviceMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alfred_common_messages_StateListMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alfred_common_messages_StateListMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021StateDevice.proto\022\032com.alfred.common.m" +
      "essages\"\352\002\n\022StateDeviceMessage\022\n\n\002id\030\001 \002" +
      "(\t\022\014\n\004name\030\002 \001(\t\022A\n\004type\030\003 \001(\01623.com.alf" +
      "red.common.messages.StateDeviceMessage.T" +
      "ype\022C\n\005state\030\004 \001(\01624.com.alfred.common.m" +
      "essages.StateDeviceMessage.State\022\r\n\005valu" +
      "e\030\005 \001(\005\022\014\n\004data\030\006 \001(\014\"K\n\004Type\022\014\n\010DOORBEL" +
      "L\020\000\022\016\n\nGARAGEDOOR\020\001\022\t\n\005LIGHT\020\002\022\016\n\nCEILIN" +
      "GFAN\020\003\022\n\n\006OUTLET\020\004\"H\n\005State\022\006\n\002ON\020\000\022\007\n\003O" +
      "FF\020\001\022\n\n\006ACTIVE\020\002\022\014\n\010INACTIVE\020\003\022\010\n\004OPEN\020\004",
      "\022\n\n\006CLOSED\020\005\"R\n\020StateListMessage\022>\n\006devi" +
      "ce\030\001 \003(\0132..com.alfred.common.messages.St" +
      "ateDeviceMessageB\023B\021StateDeviceProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_alfred_common_messages_StateDeviceMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_alfred_common_messages_StateDeviceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_alfred_common_messages_StateDeviceMessage_descriptor,
        new java.lang.String[] { "Id", "Name", "Type", "State", "Value", "Data", });
    internal_static_com_alfred_common_messages_StateListMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_alfred_common_messages_StateListMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_alfred_common_messages_StateListMessage_descriptor,
        new java.lang.String[] { "Device", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
